package com.tiki_server.enums;

public enum MessageType {
//    Server Response
    PRODUCT_INFO,
    PRODUCTS,
    CONFIGURABLE_PRODUCTS,
    PRODUCT_HISTORIES,
    CONFIGURABLE_PRODUCT_HISTORIES,
    REVIEWS,
    ERROR,

//    Client Request
    GET_PRODUCT,
    FILTER_PRODUCTS,
    GET_CONFIGURABLE_PRODUCTS,
    GET_PRODUCT_HISTORIES_BY_URL,
    GET_PRODUCT_HISTORIES_BY_PRODUCT_ID,
    GET_CONFIGURABLE_PRODUCT_HISTORIES,
    GET_REVIEWS_BY_PRODUCT_ID,

//    Connection state
    USER_DISCONNECT
}
